# Generated by Django 3.1.7 on 2021-03-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20201123_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('compliant', models.BooleanField(default=False)),
                ('business_address', models.CharField(max_length=200)),
                ('street_number', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
