# Generated by Django 3.1.7 on 2021-03-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20201123_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mopd_compliance_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
