# Generated by Django 3.1.7 on 2021-03-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_mopd_compliance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('question', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
            ],
        ),
    ]
