# Generated by Django 3.1.7 on 2021-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comment_report_ticket_comment_report_ticket_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinesafelyuser',
            name='current_geocode',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dinesafelyuser',
            name='current_location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
