# Generated by Django 3.1.7 on 2021-03-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210323_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(default='', max_length=200)),
                ('value', models.CharField(default='', max_length=200)),
                ('display_value', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='dinesafelyuser',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='user.Preferences'),
        ),
    ]
