# Generated by Django 3.1.7 on 2021-03-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210309_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='photo',
            field=models.CharField(max_length=150, null=True, verbose_name='Profile Picture'),
        ),
    ]
