# Generated by Django 3.1.7 on 2021-03-14 22:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20201123_2038'),
        ('user', '0006_auto_20210309_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=0)),
                ('rating_safety', models.PositiveIntegerField(default=0)),
                ('rating_entry', models.PositiveIntegerField(default=0)),
                ('rating_door', models.PositiveIntegerField(default=0)),
                ('rating_table', models.PositiveIntegerField(default=0)),
                ('rating_bathroom', models.PositiveIntegerField(default=0)),
                ('rating_path', models.PositiveIntegerField(default=0)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
