# Generated by Django 3.1.7 on 2021-03-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210309_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinesafelyuser',
            name='current_geocode',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dinesafelyuser',
            name='current_location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
